version: '3.8'

services:
  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URL: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"

  jupyter:
    image: jupyter/base-notebook:python-3.10.12
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      JUPYTER_TOKEN: "ecotoken"
    ports:
      - "8888:8888"

  migrator:
    build: ./backend
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
    command: ["sh", "-c", "python src/app/init_db.py && python scripts/seed_db.py && echo 'migrator done'"]
    restart: "no"

volumes:
  mongo_data:
